###  Benefits of Scala

##### Object Inititalization

Scala supports immutability:

In [1]:
val myVariable = 10 // Simple immutable variable declaration

myVariable = 10


10

In [2]:
val myList = List("scala","data") //list is immutable

myList = List(scala, data)


List(scala, data)

In [3]:
myList(1) = "other"// compile time error

Name: Compile Error
Message: <console>:28: error: value update is not a member of List[String]
       myList(1) = "other"// compile time error
       ^

StackTrace: 

Having Immutable objects removes common sources of bugs.
##### Scala promotes Functional Programming
The programmer need not worry about the iteration, compiler does that all, just tell what you want after iteration. Example:
Write a function that returns indices and element occurs in a list.

In [4]:
def occurecesOF[A](elem:A,collection:List[A]):List[Int]={
    for{
        (currentElem,index) <- collection.zipWithIndex
        if(currentElem==elem)
    } yield index
}

occurecesOF: [A](elem: A, collection: List[A])List[Int]


We tell the compiler that we want the indexes of those elements whose value is equal to our element and let the compiler worry how to iterate.

#### Numpy of Scala- Breeze
##### *Breeze vectors and matrices are mutable

In [5]:
import breeze.linalg._

In [6]:
val m = DenseMatrix((1.0,2.0,3.0),(4.0,5.0,6.0))
// Rule of thumb number of zeroes greater than 90% use sparse matrix or preferred hashedMatrix

m = 


1.0  2.0  3.0  
4.0  5.0  6.0  

In [7]:
m :* 2.0

2.0  4.0   6.0   
8.0  10.0  12.0  

In [8]:
2.0 :* m

2.0  4.0   6.0   
8.0  10.0  12.0  

In [9]:
DenseMatrix.tabulate[Int](2,3){
    (i,j) => i*2 + j
}

0  1  2  
2  3  4  

In [10]:
DenseMatrix.rand(2,3)

0.5961987061992631  0.3912002641723442  0.2939881809291962    
0.7462139045949838  0.9720833495532628  0.019694422542392953  

In [11]:
DenseVector.rand(2)

DenseVector(0.16800372909303096, 0.09154139287248197)

In [12]:
// Splat operators
val l = Seq(2,3,4)

l = List(2, 3, 4)


List(2, 3, 4)

In [13]:
DenseVector(l :_ *)

DenseVector(2, 3, 4)

### Advanced Indexing and Slicing in breeze

##### Let's start with some Vector Operations

In [14]:
// Generate a dense vector to play with
val v = DenseVector.tabulate(5){_.toDouble}

v = DenseVector(0.0, 1.0, 2.0, 3.0, 4.0)


DenseVector(0.0, 1.0, 2.0, 3.0, 4.0)

In [15]:
v(-1)// last element like python [-1]

4.0

In [16]:
v(1 to 3) // slice using range

DenseVector(1.0, 2.0, 3.0)

In [17]:
v(1 until 3) // like python [1:3]

DenseVector(1.0, 2.0)

In [18]:
v(v.length-1 to 0 by -1) // reverse view of v

DenseVector(4.0, 3.0, 2.0, 1.0, 0.0)

In [19]:
val vSlice = v(2,4) // note:view of v, no memory allocated to vSlice

vSlice = breeze.linalg.SliceVector@1aab99ff


breeze.linalg.SliceVector@1aab99ff

In [20]:
vSlice.toDenseVector // convert to Dense vector

DenseVector(2.0, 4.0)

In [21]:
val filter = v(v :<3.0) // element wise less than 

filter = breeze.linalg.SliceVector@614d2f0b


breeze.linalg.SliceVector@614d2f0b

In [22]:
filter.toDenseVector // materialize if you want to

DenseVector(0.0, 1.0, 2.0)

In [23]:
val vSlice = v (2,7) // Note: there is no v(7)

vSlice = breeze.linalg.SliceVector@6f808ede


breeze.linalg.SliceVector@6f808ede

In [24]:
vSlice(0) // runs fine

2.0

In [25]:
vSlice(1) // Throws exception

Name: java.lang.IndexOutOfBoundsException
Message: 7 not in [-5,5)
StackTrace:   at breeze.linalg.DenseVector$mcD$sp.apply$mcD$sp(DenseVector.scala:71)
  at breeze.linalg.DenseVector$mcD$sp.apply(DenseVector.scala:70)
  at breeze.linalg.DenseVector$mcD$sp.apply(DenseVector.scala:50)
  at breeze.linalg.SliceVector.apply$mcI$sp(SliceVector.scala:23)
  at breeze.linalg.SliceVector.apply(SliceVector.scala:23)
  at breeze.linalg.SliceVector.apply$mcD$sp(SliceVector.scala:23)

In [26]:
val mask = DenseVector(true,false,false,true,true) // Dense Vector for masking

mask = DenseVector(true, false, false, true, true)


lastException: Throwable = null


DenseVector(true, false, false, true, true)

In [27]:
v

DenseVector(0.0, 1.0, 2.0, 3.0, 4.0)

In [28]:
v(mask).toDenseVector

DenseVector(0.0, 3.0, 4.0)

##### Let's create a matrix to play with

In [29]:
val m = DenseMatrix((1.0,2.0,3.0),(4.0,5.0,6.0))

m = 


1.0  2.0  3.0  
4.0  5.0  6.0  

In [30]:
m(1,2) // returns scalar

6.0

In [31]:
m(1,-1) // returns scalar

6.0

In [32]:
m(0 until 2, 0 until 2) // returns a matrix

1.0  2.0  
4.0  5.0  

In [33]:
m(0 until 2,0) // returns a vector

DenseVector(1.0, 4.0)

In [34]:
m(0, 0 until 2) // returns a transpose vector

Transpose(DenseVector(1.0, 2.0))

In [35]:
m(::,1) // every element of second column

DenseVector(2.0, 5.0)

### Part -2
#### Let's see now how we can put our values in vectors and matrices

In [36]:
val v = DenseVector(1.0,2.0,3.0)

v = DenseVector(1.0, 2.0, 3.0)


DenseVector(1.0, 2.0, 3.0)

In [38]:
v(0 until 2) := DenseVector(100.0,200.0)

DenseVector(100.0, 200.0)

In [39]:
v

DenseVector(100.0, 200.0, 3.0)

In [40]:
v(0 until 2) := 9.0 // or DenseVector(9.0,9.0)

DenseVector(9.0, 9.0)

In [41]:
v

DenseVector(9.0, 9.0, 3.0)

In [42]:
v :+=4.0

DenseVector(13.0, 13.0, 7.0)

In [44]:
m :+=1.0

2.0  3.0  4.0  
5.0  6.0  7.0  

##### These Views are not independent of data, updating the view will change the whole data. Let's see..

In [ ]:
val v = DenseVector.tabulate(6){_.toDouble}

In [58]:
val viewEvens = v(0 until v.length by 2) // create view containing only even number

viewEvens = DenseVector(0.0, 2.0, 4.0)


DenseVector(0.0, 2.0, 4.0)

In [59]:
viewEvens:+=100.0

DenseVector(100.0, 102.0, 104.0)

In [60]:
v // Upadting the view also updated the original vector

DenseVector(100.0, 1.0, 102.0, 3.0, 104.0, 5.0)

In [61]:
val noView = v(0 until v.length by 2).copy

noView = DenseVector(100.0, 102.0, 104.0)


DenseVector(100.0, 102.0, 104.0)

##### Matrix multiplication and othe matrix operations

In [62]:
val m1 = DenseMatrix((2.0,3.0),(4.0,5.0),(6.0,7.0))

m1 = 


2.0  3.0  
4.0  5.0  
6.0  7.0  

In [63]:
val m2 = DenseMatrix((8.0,9.0),(10.0,11.0))

m2 = 


8.0   9.0   
10.0  11.0  

In [73]:
m1 * m2 // simple straight matrix multiplication

46.0   51.0   
82.0   91.0   
118.0  131.0  

In [74]:
// Single vector is a columnar matrix with size n*1
val v = DenseVector(10.0,5.0)

v = DenseVector(10.0, 5.0)


DenseVector(10.0, 5.0)

In [75]:
m1 * v // m1(3*2) * v(2*1)

DenseVector(35.0, 65.0, 95.0)

In [76]:
val vTranspose = v.t

vTranspose = Transpose(DenseVector(10.0, 5.0))


Transpose(DenseVector(10.0, 5.0))

In [79]:
vTranspose * m2

lastException: Throwable = null


Transpose(DenseVector(130.0, 145.0))

In [81]:
vTranspose(:+=2.0) //error: transpose vector behaves like DenseVector but does not support indexing or slicing

Name: Unknown Error
Message: <console>:1: error: ')' expected but double literal found.
vTranspose(:+=2.0) // transpose vector behaves like DenseVector but does not support indexing or slicing
              ^

StackTrace: 